import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='container-main'>
        <header>Header</header>
        {children}
         <footer>footer</footer>
        </body>
    </html>
  )
}
